### ISSUE TITLE
undefined method `join' for nil:NilClass in snippet_extractor.rb

### ISSUE THREAD

**Issue by glennfu** [rspec/rspec.tmbundle#96]
Hey all, I was just writing a spec that tests the csv_builder gem in a controller using render_views and upon calling response.body (not printing it, just calling it) I got this:

```
undefined method `join' for nil:NilClass
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/formatters/snippet_extractor.rb:77:in `lines_around'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/formatters/snippet_extractor.rb:55:in `snippet_for'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/formatters/snippet_extractor.rb:38:in `snippet'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/formatters/html_formatter.rb:142:in `extra_failure_content'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/formatters/html_formatter.rb:80:in `example_failed'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:137:in `block in notify'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:136:in `each'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:136:in `notify'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:96:in `example_failed'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:320:in `finish'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:176:in `run'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in `block in run_examples'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `run_examples'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
/Users/Glenn/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
/Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:60:in `block in run'
/Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:55:in `chdir'
/Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:55:in `run'
/Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:20:in `run_file'
/tmp/textmate-command-34147.rb:3:in `<main>'
```

rspec-core 3.0.4's snippet_extractor.rb has this:

```
        def lines_around(file, line)
          if File.file?(file)
            lines = File.read(file).split("\n")
            min = [0, line-3].max
            max = [line+1, lines.length-1].min
            selected_lines = []
            selected_lines.join("\n")
            lines[min..max].join("\n")
          else
            "# Couldn't get snippet for #{file}"
          end
        rescue SecurityError
          "# Couldn't get snippet for #{file}"
        end
```

changing this part:
```
            selected_lines = []
            selected_lines.join("\n")
            lines[min..max].join("\n")
```

to this:
```
            selected_lines = []
            selected_lines.join("\n")
            rez_lines = lines[min..max]
            rez_lines ? rez_lines.join("\n") : ""
```

Fixes my issue, and now my stack trace looks like this:
```
undefined method `category' for #<Ajam::Story:0x007fd5820709b8>
./app/views/move_logs/index.csv.csvbuilder:27:in `block (2 levels) in _app_views_move_logs_index_csv_csvbuilder__4041493767658285204_70277493047580'
./app/views/move_logs/index.csv.csvbuilder:22:in `block in _app_views_move_logs_index_csv_csvbuilder__4041493767658285204_70277493047580'
./spec/controllers/move_logs_controller_spec.rb:34:in `block (2 levels) in <top (required)>'
```

which is a much more meaningful failure. If I run `rake spec` in the console I get the same meaningful error with the original code. Do you guys think this is a problem with the way we're passing something to rspec from the bundle?

I'd take the time to build a smaller test case, but typically when I try to do that, it gets fixed and released before I finish building my test case ;) Let me know if you need more information.

**Comment by noniq** [comment]
Is this still an issue?

**Comment by noniq** [comment]
Closing because it seems stale. Feel free to reopen, though.
