### ISSUE TITLE
rspec-core 3.3.2 - broken when displaying a failed example

### ISSUE THREAD

**Issue by glennfu** [rspec/rspec.tmbundle#99]
After upgrading rspec-core (and the rest of rspec-rails) from 3.2.3 to 3.3.2, I started seeing this whenever a spec failed. I haven't yet dug into it.

```
ArgumentError: wrong number of arguments (7 for 6)

/Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/formatters/html_printer.rb:37:in `print_example_failed'
  /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/text_mate_formatter.rb:21:in `print_example_failed'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/formatters/html_formatter.rb:80:in `example_failed'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:184:in `block in notify'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:183:in `each'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:183:in `notify'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:135:in `example_failed'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:404:in `finish'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:363:in `fail_with_exception'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:529:in `block in run'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:567:in `each'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:567:in `for_filtered_examples'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:571:in `block in for_filtered_examples'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:569:in `each'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:569:in `for_filtered_examples'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:529:in `rescue in run'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:534:in `run'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
  /Users/Glenn/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
  /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:60:in `block in run'
  /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:55:in `chdir'
  /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:55:in `run'
  /Users/Glenn/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/runner.rb:20:in `run_file'
  /tmp/textmate-command-64888.rb:3:in `<main>'
```

**Comment by glennfu** [comment]
Here's my proposed change to HtmlPrinterWithClickableBacktrace:

```
module RSpec
  module Mate
    module Formatters
      class HtmlPrinterWithClickableBacktrace < RSpec::Core::Formatters::HtmlPrinter
        
        def print_example_failed(pending_fixed, description, run_time, failure_id, exception, extra_content, escape_backtrace = false)
          exception[:backtrace] = make_backtrace_clickable(exception[:backtrace])
          # Call original implementation, but pass false for `escape_backtrace`

          original_arg_count = self.class.superclass.instance_method(__method__).arity

          if original_arg_count == 6
            extra_content = extra_content.to_s
            extra_content += "        <div class=\"message\"><pre>#{h(exception[:message])}</pre></div>"
            extra_content += "        <div class=\"backtrace\"><pre>#{exception[:backtrace]}</pre></div>"
            exception = nil
          
            super(pending_fixed, description, run_time, failure_id, exception, extra_content)
          else
            super(pending_fixed, description, run_time, failure_id, exception, extra_content, false)
          end
        end
      end
      
    end
  end
end
```

What do you all think of that?

**Comment by noniq** [comment]
Is your bundle up to date? This should have been fixed with https://github.com/rspec/rspec.tmbundle/commit/d3644929e12edd01d2410ed6aa209735b8227398 some time ago.

**Comment by noniq** [comment]
Closing because it seems stale – feel free to reopen if necessary!
